pycharm/MyBlog/MyBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blogapp.urls')),
]

pycharm/MyBlog/blogapp/models.py
from django.db import models
from userapp.models import BlogUser


# Create your models here.

# 轮播图
class Banner(models.Model):
    title = models.CharField(verbose_name='标题', max_length=20)
    cover = models.ImageField('封面', upload_to='static/imgs/banner')
    link_url = models.URLField('链接', max_length=256)
    idx = models.IntegerField('索引')
    is_active = models.BooleanField('是否被激活', default=False)

    def __str__(self):
        return self.title

    class Meta:  # 元选项
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name


# 分类字段
class Category(models.Model):
    name = models.CharField('名字', max_length=20)

    def __str__(self):
        return self.name

    class Meta:  # 元选项
        verbose_name = '分类'
        verbose_name_plural = verbose_name


# 标签
class Tags(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:  # 元选项
        verbose_name = '标签'
        verbose_name_plural = verbose_name


# 文章类
class Post(models.Model):
    user = models.ForeignKey(BlogUser,verbose_name='作者')
    category = models.ForeignKey(Category,verbose_name='分类')
    tags = models.ManyToManyField(Tags,verbose_name='标签')
    title = models.CharField(max_length=50,verbose_name='标题')
    cover = models.ImageField(upload_to='static/imgs/post',verbose_name='封面')
    pub_date = models.DateTimeField('发布日期')
    views = models.IntegerField(default=0,verbose_name='浏览量')
    content = models.TextField(verbose_name='内容')
    recommend = models.BooleanField(default=False,verbose_name='推荐')

    def __str__(self):
        return self.title

    class Meta:  # 元选项
        verbose_name = '文章'
        verbose_name_plural = verbose_name


# 友情链接
class Link(models.Model):
    name = models.CharField(max_length=20,verbose_name='名字')
    link_url = models.URLField(max_length=256, default='',verbose_name='链接')

    def __str__(self):
        return self.name

    class Meta:  # 元选项
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name


# 评论内容
class Comment(models.Model):
    user = models.ForeignKey(BlogUser,verbose_name='用户')
    post = models.ForeignKey(Post,verbose_name='文章')
    content = models.CharField(max_length=256,verbose_name='内容')
    comment_date = models.DateTimeField(verbose_name='评论日期')

    def __str__(self):
        return self.content

    class Meta:  # 元选项
        verbose_name = '评论'
        verbose_name_plural = verbose_name

pycharm/MyBlog/templates/_pagination.html
{% load i18n %}
<div class="pagination">
    {% if post_all_list.has_previous %}
        <a href="?{{ post_all_list.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; 上一页</a>
    {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; 上一页</span>
    {% endif %}
    {% for page in post_all_list.pages %}
        {% if page %}
            {% ifequal page post_all_list.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if post_all_list.has_next %}
        <a href="?{{ post_all_list.next_page_number.querystring }}" class="next">下一页 &rsaquo;&rsaquo;</a>
    {% else %}
        <span class="disabled next">下一页 &rsaquo;&rsaquo;</span>
    {% endif %}
</div>

pycharm/MyBlog/templates/base.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}博客{% endblock %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/nprogress.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
    <link rel="apple-touch-icon-precomposed" href="/static/images/icon.png">
    <link rel="shortcut icon" href="/static/images/favicon.ico">

    {% block custom_css %} {% endblock %}
    <script src="/static/js/jquery-2.1.4.min.js"></script>
    <script src="/static/js/nprogress.js"></script>
    <script src="/static/js/jquery.lazyload.min.js"></script>
    <!--[if gte IE 9]>
      <script src="js/jquery-1.11.1.min.js" type="text/javascript"></script>
      <script src="js/html5shiv.min.js" type="text/javascript"></script>
      <script src="js/respond.min.js" type="text/javascript"></script>
      <script src="js/selectivizr-min.js" type="text/javascript"></script>
    <![endif]-->
    <!--[if lt IE 9]>
      <script>window.location.href='upgrade-browser.html';</script>
    <![endif]-->
</head>
<body class="user-select">
<header class="header">
    <nav class="navbar navbar-default" id="navbar">
        <div class="container">
            <div class="header-topbar hidden-xs link-border">
                <ul class="site-nav topmenu">
                    <li><a href="http://www.baidu.com/tags/">标签云</a></li>
                    <li><a href="http://www.baidu.com/readers/" rel="nofollow">读者墙</a></li>
                    <li><a href="http://www.baidu.com/rss.html" title="RSS订阅">
                        <i class="fa fa-rss">
                        </i> RSS订阅
                    </a></li>
                </ul>
                勤记录 懂分享
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#header-navbar" aria-expanded="false"><span class="sr-only"></span> <span
                        class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
                <h1 class="logo hvr-bounce-in"><a href="http://www.baidu.com/" title="网络博客"><img
                        src="/static/images/favicon.ico" alt="网络博客"></a></h1>
            </div>
            <div class="collapse navbar-collapse" id="header-navbar">
                <form class="navbar-form visible-xs" action="/search/" method="post">
                    <div class="input-group">
                        <input type="text" name="keyword" class="form-control" placeholder="请输入关键字" maxlength="20"
                               autocomplete="off">

                        <span class="input-group-btn">
            <button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
            </span></div>
                    {% csrf_token %}
                </form>
                <ul class="nav navbar-nav navbar-left">
                    <li><a data-cont="网络博客" title="网络博客" href="/index/">首页</a></li>
                    <li><a data-cont="列表页" title="列表页" href="/list/">列表页</a></li>

                </ul>

                {% if user.is_authenticated %}

                    <ul class="nav navbar-nav navbar-right">
                        <li><a data-cont="网络博客" title="网络博客" href="#">欢迎：{{ user.username }}</a></li>
                        <li><a data-cont="列表页" title="列表页" href="/loginout/">注销</a></li>

                    </ul>

                {% else %}

                    <ul class="nav navbar-nav navbar-right">
                        <li><a data-cont="网络博客" title="网络博客" href="/login/">登录</a></li>
                        <li><a data-cont="列表页" title="列表页" href="/register/">注册</a></li>

                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

{% block content %}{% endblock %}

<footer class="footer">
    <div class="container">
        <p>本站[<a href="http://www.baidu.com/">网络博客</a>]的部分内容来源于网络，若侵犯到您的利益，请联系站长删除！谢谢！Powered By [<a
                href="http://www.dtcms.net/" target="_blank" rel="nofollow">DTcms</a>] Version 4.0 &nbsp;<a
                href="http://www.miitbeian.gov.cn/" target="_blank" rel="nofollow">闽ICP备00000000号-1</a> &nbsp; <a
                href="http://www.baidu.com/sitemap.xml" target="_blank" class="sitemap">网站地图</a></p>
    </div>
    <div id="gotop"><a class="gotop"></a></div>
</footer>
<script src="/static/js/bootstrap.min.js"></script>
{#<script src="/static/js/jquery.ias.js"></script>#}
<script src="/static/js/scripts.js">

</script>
</body>
</html>

pycharm/MyBlog/templates/forpwd.html
{% extends 'base.html' %}
{% block title %}知奇博客-找回密码 {% endblock %}

{% block custom_css %}
    <style type="text/css">
        .panel {
            padding: 80px 20px 0px;
            min-height: 400px;
            cursor: default;
        }

        .text-center {
            margin: 0 auto;
            text-align: center;
            border-radius: 10px;
            max-width: 900px;
            -moz-box-shadow: 0px 0px 5px rgba(0, 0, 0, .3);
            -webkit-box-shadow: 0px 0px 5px rgba(0, 0, 0, .3);
            box-shadow: 0px 0px 5px rgba(0, 0, 0, .1);
        }

        .float-left {
            float: left !important;
        }

        .float-right {
            float: right !important;
        }

        img {
            border: 0;
            vertical-align: bottom;
        }

        h2 {
            padding-top: 20px;
            font-size: 20px;
        }

        .padding-big {
            padding: 20px;
        }

        .alert {
            border-radius: 5px;
            padding: 15px;
            border: solid 1px #ddd;
            background-color: #f5f5f5;
        }
    </style>

{% endblock %}


{% block content %}


    <section class="container">
        <div class="panel">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <p style="color:red">{{ error }}</p>
                    <form action="/forget/" method="post">

                        <div class="form-group">

                            <label for="exampleInputEmail1">邮箱</label>
                            <input type="text" name='email' class="form-control" id="exampleInputEmail1"
                                   placeholder="请输入邮箱...">
                        </div>



                        <button type="submit" class="btn btn-default">提交</button>
                        {% csrf_token %}
                    </form>

                </div>

            </div>
        </div>
    </section>

{% endblock %}

pycharm/MyBlog/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <section class="container">
        <div class="content-wrap">
            <div class="content">
                <div id="focusslide" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">

                        {#                    轮播图#}
                        {% for banner in banner_list %}
                            {% if banner.is_active %}
                                <li data-target="#focusslide" data-slide-to="{{ forloop.counter }}" class="active"></li>
                            {% else %}
                                <li data-target="#focusslide" data-slide-to="{{ forloop.counter }}"></li>
                            {% endif %}
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        {% for banner in banner_list %}
                            {% if banner.is_active %}

                                <div class="item active">
                                    <a href="{{ banner.link_url }}" target="_blank" title="{{ banner.title }}">
                                        <img src="/{{ banner.cover }}" alt="{{ banner.title }}"
                                             item class="img-responsive"></a>
                                </div>
                            {% else %}
                                <div class="item">
                                    <a href="{{ banner.link_url }}" target="_blank" title="{{ banner.title }}">
                                        <img src="/{{ banner.cover }}" alt="{{ banner.title }}"
                                             item class="img-responsive"></a>
                                </div>

                            {% endif %}
                        {% endfor %}


                    </div>


                    <a class="left carousel-control" href="#focusslide" role="button" data-slide="prev" rel="nofollow">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span
                            class="sr-only">上一个</span> </a> <a class="right carousel-control" href="#focusslide"
                                                               role="button" data-slide="next" rel="nofollow"> <span
                        class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span
                        class="sr-only">下一个</span> </a>

                </div>


                {#        推荐#}

                {% for post in post_list %}
                    <article class="excerpt-minic excerpt-minic-index">
                        <h2><span class="red">【推荐】</span><a target="_blank" href="/show/{{ post.id }}"
                                                            title="{{ post.title }}">{{ post.title }}</a>
                        </h2>
                        <p class="note">{{ post.content }}</p>
                    </article>


                {% endfor %}


                <div class="title">
                    <h3>最新发布</h3>
                    <div class="more">
                        {#                    分类#}
                        {% for category in category_list %}
                            <a href="/category/{{ category.id }}/" title="{{ category.name }}">{{ category.name }}</a>
                        {% endfor %}

                    </div>
                </div>


                {% for post in new_post_list %}
                    <article class="excerpt excerpt-1" style="">
                        <a class="focus" href="/show/{{ post.id }}" title="{{ post.title }}"
                           target="_blank">
                            <img class="thumb"
                                 data-original="/{{ post.cover }}"
                                 src="/{{ post.cover }}"
                                 alt="{{ post.title }}" style="display: inline;"></a>
                        <header><a class="cat" href="/show/{{ post.id }}"
                                   title="{{ post.category.name }}">{{ post.category.name }}<i></i></a>
                            <h2><a href="/show/{{ post.id }}" title="{{ post.title }}"
                                   target="_blank">{{ post.title }}</a>
                            </h2>
                        </header>
                        <p class="meta">
                            <time class="time"><i class="glyphicon glyphicon-time"></i> {{ post.pub_date|date:'Y-m-d' }}
                            </time>
                            <span class="views"><i class="glyphicon glyphicon-eye-open"></i> {{ post.views }}</span> <a
                                class="comment"
                                href="#"
                                title="评论"
                                target="_blank"><i
                                class="glyphicon glyphicon-comment"></i> {{ post.comment_set.count }}</a>
                        </p>
                        <p class="note">{{ post.content }}</p>
                    </article>

                {% endfor %}


                <nav class="pagination" style="display: none;">
                    <ul>
                        <li class="prev-page"></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="?page=2">2</a></li>
                        <li class="next-page"><a href="?page=2">下一页</a></li>
                        <li><span>共 2 页</span></li>
                    </ul>
                </nav>
            </div>
        </div>
        <aside class="sidebar">
            <div class="fixed">
                <div class="widget widget-tabs">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#notice" aria-controls="notice" role="tab"
                                                                  data-toggle="tab">统计信息</a></li>
                        <li role="presentation"><a href="#contact" aria-controls="contact" role="tab"
                                                   data-toggle="tab">联系站长</a></li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane contact active" id="notice">
                            <h2>日志总数:
                                888篇
                            </h2>
                            <h2>网站运行:
                                <span id="sitetime">88天 </span></h2>
                        </div>
                        <div role="tabpanel" class="tab-pane contact" id="contact">
                            <h2>QQ:
                                <a href="http://wpa.qq.com/msgrd?v=3&amp;uin=1234&amp;site=qq&amp;menu=yes"
                                   target="_blank"
                                   rel="nofollow" data-toggle="tooltip" data-placement="bottom" title=""
                                   data-original-title="QQ:496155678">496155678</a>
                            </h2>
                            <h2>Email:
                                <a href="mailto:1234@qq.com" target="_blank" data-toggle="tooltip" rel="nofollow"
                                   data-placement="bottom" title=""
                                   data-original-title="Email:1234@qq.com">1234@qq.com</a>
                            </h2>
                        </div>
                    </div>
                </div>
                <div class="widget widget_search">
                    <form class="navbar-form" action="/search/" method="get">
                        <div class="input-group">
                            <input type="text" name="keyword" class="form-control" size="35" placeholder="请输入关键字"
                                   maxlength="15" autocomplete="off">
                            <span class="input-group-btn">
            <button class="btn btn-default btn-search" type="submit">搜索</button>
            </span></div>
                    </form>
                </div>
            </div>


            <div class="widget widget_hot">
                <h3>最新评论文章</h3>
                <ul>

                    {% for comment in comment_list %}
                        <li>
                            <a title="{{ comment.post.title }}" href="/show/{{ comment.post.id }}">

                            <span class="thumbnail">
                    <img class="thumb" data-original="/{{ comment.post.cover }}"
                         src="/{{ comment.post.cover }}" alt="{{ comment.post.title }}"
                         style="display: block;">
                </span>

                                <span class="text">{{ comment.post.title }}</span>

                                <span class="muted"><i
                                        class="glyphicon glyphicon-time">{{ comment.post.pub_date|date:'Y-m-d' }}</i>

                </span>


                                <span class="muted"><i
                                        class="glyphicon glyphicon-eye-open"></i>{{ comment.post.views }}</span></a>

                        </li>

                    {% endfor %}


                </ul>
            </div>
            {#            <div class="widget widget_sentence">#}
            {#                <a href="http://www.baidu.com//" target="_blank" rel="nofollow" title="专业网站建设">#}
            {#                    <img style="width: 100%" src="/static/images/ad.jpg"#}
            {#                         alt="专业网站建设"></a>#}
            {#            </div>#}

            <div class="widget widget_sentence">
                <h3>友情链接</h3>

                <div class="widge-sentence-link">
                    {% for link in friend_list %}
                        <a style="margin: 10px" href="{{ link.link_url }}" title="{{ link.name }}"
                           target="_blank">{{ link.name }}</a>&nbsp;
                        &nbsp;&nbsp;
                    {% endfor %}
                </div>

            </div>
        </aside>
    </section>
{% endblock %}

pycharm/MyBlog/templates/list.html
{% extends 'base.html' %}

{% block content %}
    <section class="container">
        <div class="content-wrap">
            <div class="content">
                <div class="title">
                    <h3 style="line-height: 1.3">MZ-NetBlog主题</h3>
                </div>

                {% for post in post_all_list.object_list %}
                    <article class="excerpt excerpt-1"><a class="focus" href="/show/{{ post.id }}"
                                                          title="{{ post.title }}" target="_blank">

                        <img class="thumb"
                             data-original="/{{ post.cover }}"
                             src="/{{ post.cover }}"
                             alt="{{ post.title }}"
                             style="display: inline;">
                    </a>
                        <header><a class="cat" href="/show/{{ post.id }}"
                                   title="{{ post.category.name }}">{{ post.category.name }}<i></i></a>
                            <h2><a href="/show/{{ post.id }}" title="{{ post.title }}"
                                   target="_blank">{{ post.title }}</a>
                            </h2>
                        </header>
                        <p class="meta">
                            <time class="time"><i class="glyphicon glyphicon-time"></i> {{ post.pub_date|date:'Y-m-d' }}
                            </time>
                            <span class="views"><i class="glyphicon glyphicon-eye-open"></i> {{ post.views }}</span> <a
                                class="comment"
                                href="http://www.baidu.com/show/269.html#comment"
                                title="评论"
                                target="_blank"><i
                                class="glyphicon glyphicon-comment"></i> {{ post.comment_set.count }}</a></p>
                        <p class="note">{{ post.content }}</p>
                    </article>

                {% endfor %}

                {% include "_pagination.html" %}


                {#                <nav class="pagination" style="display: none;">#}
                {#                    <ul>#}
                {#                        <li class="prev-page"></li>#}
                {#                        <li class="active"><span>1</span></li>#}
                {#                        <li><a href="?page=2">2</a></li>#}
                {#                        <li class="next-page"><a href="?page=2">下一页</a></li>#}
                {#                        <li><span>共 2 页</span></li>#}
                {#                    </ul>#}
                {#                </nav>#}
            </div>
        </div>
        <aside class="sidebar">
            <div class="fixed">
                <div class="widget widget_search">
                    <form class="navbar-form" action="/search/" method="post">
                        <div class="input-group">
                            <input type="text" name="keyword" class="form-control" size="35" placeholder="请输入关键字"
                                   maxlength="15" autocomplete="off">
                            <span class="input-group-btn">
            <button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
            </span></div>

                        {% csrf_token %}
                    </form>
                </div>
                <div class="widget widget_sentence">
                    <h3>标签云</h3>
                    <div class="widget-sentence-content">
                        <ul class="plinks ptags">

                            {% for tag in tag_list %}
                                <li><a href="/tags/{{ tag.id }}/" title="{{ tag.name }}"
                                       draggable="false">{{ tag.name }}
                                    <span
                                            class="badge">{{ tag.post_set.count }}</span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="widget widget_hot">
                <h3>最新评论文章</h3>
                <ul>

                    {% for comment in comment_list %}
                        <li>
                            <a title="{{ comment.post.title }}" href="/show/{{ comment.post.id }}">

                            <span class="thumbnail">
                    <img class="thumb" data-original="{{ comment.post.cover }}"
                         src="/{{ comment.post.cover }}" alt="{{ comment.post.title }}"
                         style="display: block;">
                </span>

                                <span class="text">{{ comment.post.title }}</span>

                                <span class="muted"><i
                                        class="glyphicon glyphicon-time">{{ comment.post.pub_date|date:'Y-m-d' }}</i>

                </span>


                                <span class="muted"><i
                                        class="glyphicon glyphicon-eye-open"></i>{{ comment.post.views }}</span></a>

                        </li>

                    {% endfor %}
                </ul>
            </div>
            <div class="widget widget_sentence">

                <a href="http://www.baidu.com/show/269.html" target="_blank" rel="nofollow" title="MZ-NetBlog主题">
                    <img style="width: 100%" src="/static/images/ad.jpg" alt="MZ-NetBlog主题"></a>

            </div>
            <div class="widget widget_sentence">

                <a href="http://web.baidu.com/" target="_blank" rel="nofollow" title="专业网站建设">
                    <img style="width: 100%" src="http://www.baidu.com/upload/201610/24/201610241224221511.jpg"
                         alt="专业网站建设"></a>

            </div>
        </aside>
    </section>
{% endblock %}

pycharm/MyBlog/templates/login.html
{% extends 'base.html' %}
{% block title %}知奇博客-详细 {% endblock %}

{% block custom_css %}
    <style type="text/css">
        .panel {
            padding: 80px 20px 0px;
            min-height: 400px;
            cursor: default;
        }

        .text-center {
            margin: 0 auto;
            text-align: center;
            border-radius: 10px;
            max-width: 900px;
            -moz-box-shadow: 0px 0px 5px rgba(0, 0, 0, .3);
            -webkit-box-shadow: 0px 0px 5px rgba(0, 0, 0, .3);
            box-shadow: 0px 0px 5px rgba(0, 0, 0, .1);
        }

        .float-left {
            float: left !important;
        }

        .float-right {
            float: right !important;
        }

        img {
            border: 0;
            vertical-align: bottom;
        }

        h2 {
            padding-top: 20px;
            font-size: 20px;
        }

        .padding-big {
            padding: 20px;
        }

        .alert {
            border-radius: 5px;
            padding: 15px;
            border: solid 1px #ddd;
            background-color: #f5f5f5;
        }
    </style>

{% endblock %}


{% block content %}


    <section class="container">
        <div class="panel">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <p style="color:red">{{ error }}</p>
                    <form action="/login/" method="post">

                        <div class="form-group">

                            <label for="exampleInputEmail1">用户名称</label>
                            <input type="text" name='username' class="form-control" id="exampleInputEmail1"
                                   placeholder="请输入用户名称...">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">密码</label>
                            <input type="password" name='password' class="form-control" id="exampleInputPassword1"
                                   placeholder="请输入密码...">
                        </div>

                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> 自动登录
                            </label>

                            <label>
                                <a  style="margin-left: 200px" href="/forget/">忘记密码</a>
                            </label>


                        </div>
                        <button type="submit" class="btn btn-default">登录</button>
                        {% csrf_token %}
                    </form>

                </div>

            </div>
        </div>
    </section>

{% endblock %}

pycharm/MyBlog/templates/register.html
{% extends 'base.html' %}
{% block title %}知奇博客-注册{% endblock %}

{% block custom_css %}
<style type="text/css">
	.panel
	{
		padding: 80px 20px 0px;
		min-height: 400px;
		cursor: default;
	}
	.text-center
	{
		margin: 0 auto;
		text-align: center;
		border-radius: 10px;
		max-width: 900px;
		-moz-box-shadow: 0px 0px 5px rgba(0,0,0,.3);
		-webkit-box-shadow: 0px 0px 5px rgba(0,0,0,.3);
		box-shadow: 0px 0px 5px rgba(0,0,0,.1);
	}
	.float-left
	{
		float: left !important;
	}
	.float-right
	{
		float: right !important;
	}
	img
	{
		border: 0;
		vertical-align: bottom;
	}
	h2
	{
		padding-top: 20px;
		font-size: 20px;
	}
	.padding-big
	{
		padding: 20px;
	}
	.alert
	{
		border-radius: 5px;
		padding: 15px;
		border: solid 1px #ddd;
		background-color: #f5f5f5;
	}
</style>

{% endblock %}


{% block content %}


<section class="container">
<div class="panel">
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<p style="color:red">{{error}}</p>
		<form action="/register/" method="post">
	  <div class="form-group">
	    <label for="exampleInputEmail1">用户名称</label>
	    <input type="text" name='username' class="form-control" id="exampleInputEmail1" placeholder="请输入用户名称...">
	  </div>

	  <div class="form-group">
	    <label for="exampleInputPassword1">密码</label>
	    <input type="password" name='password' class="form-control" id="exampleInputPassword1" placeholder="请输入密码...">
	  </div>

		<div class="form-group">
			<label for="exampleInputEmail">邮箱</label>
			<input type="email" name='email' class="form-control" id="exampleInputEmail" placeholder="请输入邮箱...">
		</div>

	  <button type="submit" class="btn btn-default">注册</button>
		{% csrf_token %}
	</form>

</div>

</div>
</div>
</section>

{% endblock %}